spring.application.name=Java_Web_Service_Project

spring.datasource.url=jdbc:mysql://localhost:3306/java_webservice_project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



jwt.secret=asdfghjkwertylsdghjklfghjkwertyuiop
jwt.access-token.expiration=900000
# 15 phut
jwt.refresh-token.expiration=604800000
# 7 ngay

# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB


# CLOUDINARY
cloudinary.cloud-name=phuonglinh
cloudinary.api-key=566662242453444
cloudinary.api-secret=Cmznbu0d08FY9tNI5yTnweersbU
cloudinary.secure=true


logging.level.com.example.coursemanagement=DEBUG
logging.level.org.springframework.security=INFO


#spring.jackson.serialization.write-dates-as-timestamps=false
#spring.jackson.time-zone=Asia/Ho_Chi_Minh


# MAIL (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=plinhle26@gmail.com
spring.mail.password=lijl hvfi tbvf cxqe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# OTP h?t h?n sau 5 phút (giây)
otp.expiration-seconds=300


# REDIS
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
## N?u Redis có password:
## spring.data.redis.password=yourpassword